# Generated by Django 5.0.5 on 2024-05-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarto',
            name='descricao',
            field=models.TextField(max_length=230),
        ),
    ]
